server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: ${kafka.bootstrap.servers} # 你的Kafka地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: manual_immediate
  jackson:
    default-property-inclusion: non_null
hmdp:
  db:
    database: ${db.shop} # 你的数据库名称
  mp:
    package: shop
  swagger:
    title: 店铺服务接口文档
    package: com.hmdp.shop.controller
canal:
  filter: 'hmdp_shop\.business_outbox,hmdp_shop\.tb_shop_type'
